<<<<<<< HEAD
name: CI/CD Backend
=======
name: Deploy to Docker

>>>>>>> 65c068652598bdf7334581405f3f0f54e48a4963
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
=======

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

>>>>>>> 65c068652598bdf7334581405f3f0f54e48a4963
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker-compose build
<<<<<<< HEAD
          docker-compose up -d
=======
>>>>>>> 65c068652598bdf7334581405f3f0f54e48a4963
          docker-compose push
