name: CI/CD Backend

on:
  push:
    branches:
      - main  # Cambia esto si quieres que se ejecute en otra rama

jobs:
  build:
    runs-on: ubuntu-latest  # Especificamos que el trabajo se ejecutar치 en un entorno Ubuntu

    steps:
      # Paso 1: Obtener el c칩digo del repositorio
      - name: Checkout Code
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker Buildx para construir las im치genes de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Iniciar sesi칩n en DockerHub utilizando los secretos configurados
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 4: Construir y subir la imagen Docker utilizando docker-compose
      - name: Build and Push Docker Image
        run: |
          # Construir la imagen de Docker con docker-compose
          docker-compose build

          # Levantar los contenedores en segundo plano
          docker-compose up -d

          # Subir la imagen a DockerHub (si tienes un registro configurado en tu docker-compose.yml)
          docker-compose push

      # Paso 5: Limpiamos contenedores para evitar que queden corriendo innecesariamente
      - name: Clean up Docker containers
        run: |
          docker-compose down
